// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: proto/proxy.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ---------------------------------------------------------------------------
// Client-side interface
// ---------------------------------------------------------------------------

// InferenceServiceClient is the client API for InferenceService.
type InferenceServiceClient interface {
	Infer(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error)
	InferStream(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (InferenceService_InferStreamClient, error)
}

type inferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceServiceClient(cc grpc.ClientConnInterface) InferenceServiceClient {
	return &inferenceServiceClient{cc}
}

func (c *inferenceServiceClient) Infer(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error) {
	out := new(InferenceResponse)
	err := c.cc.Invoke(ctx, "/inferenceproxy.InferenceService/Infer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) InferStream(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (InferenceService_InferStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &InferenceService_ServiceDesc.Streams[0], "/inferenceproxy.InferenceService/InferStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &inferenceServiceInferStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// InferenceService_InferStreamClient is the client-side streaming interface.
type InferenceService_InferStreamClient interface {
	Recv() (*StreamChunk, error)
	grpc.ClientStream
}

type inferenceServiceInferStreamClient struct {
	grpc.ClientStream
}

func (x *inferenceServiceInferStreamClient) Recv() (*StreamChunk, error) {
	m := new(StreamChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ---------------------------------------------------------------------------
// Server-side interface
// ---------------------------------------------------------------------------

// InferenceServiceServer is the server API for InferenceService.
type InferenceServiceServer interface {
	Infer(context.Context, *InferenceRequest) (*InferenceResponse, error)
	InferStream(*InferenceRequest, InferenceService_InferStreamServer) error
	mustEmbedUnimplementedInferenceServiceServer()
}

// UnimplementedInferenceServiceServer should be embedded to have forward
// compatible implementations.
type UnimplementedInferenceServiceServer struct{}

func (UnimplementedInferenceServiceServer) Infer(context.Context, *InferenceRequest) (*InferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Infer not implemented")
}

func (UnimplementedInferenceServiceServer) InferStream(*InferenceRequest, InferenceService_InferStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method InferStream not implemented")
}

func (UnimplementedInferenceServiceServer) mustEmbedUnimplementedInferenceServiceServer() {}

// UnsafeInferenceServiceServer may be embedded to opt out of forward
// compatibility for this service.
type UnsafeInferenceServiceServer interface {
	mustEmbedUnimplementedInferenceServiceServer()
}

// InferenceService_InferStreamServer is the server-side streaming interface.
type InferenceService_InferStreamServer interface {
	Send(*StreamChunk) error
	grpc.ServerStream
}

type inferenceServiceInferStreamServer struct {
	grpc.ServerStream
}

func (x *inferenceServiceInferStreamServer) Send(m *StreamChunk) error {
	return x.ServerStream.SendMsg(m)
}

// ---------------------------------------------------------------------------
// Service registration
// ---------------------------------------------------------------------------

func RegisterInferenceServiceServer(s grpc.ServiceRegistrar, srv InferenceServiceServer) {
	s.RegisterService(&InferenceService_ServiceDesc, srv)
}

func _InferenceService_Infer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).Infer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inferenceproxy.InferenceService/Infer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).Infer(ctx, req.(*InferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_InferStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InferenceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InferenceServiceServer).InferStream(m, &inferenceServiceInferStreamServer{stream})
}

// InferenceService_ServiceDesc is the grpc.ServiceDesc for InferenceService.
var InferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inferenceproxy.InferenceService",
	HandlerType: (*InferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Infer",
			Handler:    _InferenceService_Infer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InferStream",
			Handler:       _InferenceService_InferStream_Handler,
			ServerStreams:  true,
		},
	},
	Metadata: "proto/proxy.proto",
}
